from io import BytesIO
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

try:
    pdfmetrics.registerFont(TTFont("Inter", "Inter-Regular.ttf"))
    FONT="Inter"
except:
    FONT="Helvetica"

styles=getSampleStyleSheet()

title_style=ParagraphStyle("Title",parent=styles["Heading1"],fontName=FONT,fontSize=24,alignment=TA_CENTER,textColor=colors.HexColor("#4F46E5"),spaceAfter=8)
subtitle_style=ParagraphStyle("Sub",parent=styles["BodyText"],fontName=FONT,fontSize=10,alignment=TA_CENTER,textColor=colors.grey,spaceAfter=12)
heading_style=ParagraphStyle("Head",parent=styles["Heading2"],fontName=FONT,fontSize=16,textColor=colors.HexColor("#4F46E5"),spaceAfter=6)
body_style=ParagraphStyle("Body",parent=styles["BodyText"],fontName=FONT,fontSize=11,leading=20)
bullet_style=ParagraphStyle("Bullet",parent=body_style,leftIndent=15)

def heading(t): return Paragraph(t, heading_style)
def normal(t): return Paragraph(str(t), body_style)

def bullet_section(title, items):
    out=[heading(title),Spacer(1,6)]
    if not items:
        out.append(normal("Not Available"))
    else:
        for i in items:
            out.append(Paragraph("• "+str(i), bullet_style))
    out.append(Spacer(1,12))
    return out

def score_card(score):
    if score>=90: bg=colors.HexColor("#10B981")
    elif score>=80: bg=colors.HexColor("#FACC15")
    elif score>=70: bg=colors.HexColor("#F97316")
    else: bg=colors.HexColor("#EF4444")
    tbl=Table([[Paragraph(f"<para align='center'><font color='white' size='22'><b>{score}/100</b></font></para>",body_style)]],colWidths=[6*inch])
    tbl.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,-1),bg),
        ("TOPPADDING",(0,0),(-1,-1),18),
        ("BOTTOMPADDING",(0,0),(-1,-1),18),
    ]))
    return tbl

def generate_pdf(analysis):
    buffer=BytesIO()
    doc=SimpleDocTemplate(buffer,leftMargin=40,rightMargin=40,topMargin=45,bottomMargin=40)
    story=[]
    story.append(Paragraph("CVision",title_style))
    story.append(Paragraph("AI Resume Analysis Report",subtitle_style))
    story.append(Paragraph(datetime.now().strftime("Generated on %d %B %Y"),subtitle_style))
    story.append(Spacer(1,16))
    story.append(heading("Overall ATS Score"))
    story.append(score_card(analysis["ats_score"]))
    story.append(Spacer(1,18))
    story.append(heading("Section Scores"))
    rows=[
        ["Section","Score"],
        ["Technical Skills",f'{analysis["section_scores"]["technical_skills"]}/20'],
        ["Projects",f'{analysis["section_scores"]["projects"]}/25'],
        ["Experience",f'{analysis["section_scores"]["experience"]}/20'],
        ["Education",f'{analysis["section_scores"]["education"]}/10'],
        ["Formatting",f'{analysis["section_scores"]["formatting"]}/10'],
        ["Keyword Optimization",f'{analysis["section_scores"]["keyword_optimization"]}/15'],
    ]
    table=Table(rows,colWidths=[4.5*inch,1.3*inch])
    table.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#4F46E5")),
        ("TEXTCOLOR",(0,0),(-1,0),colors.white),
        ("GRID",(0,0),(-1,-1),0.4,colors.grey),
        ("BACKGROUND",(0,1),(-1,-1),colors.whitesmoke),
        ("FONTNAME",(0,0),(-1,-1),FONT),
        ("ALIGN",(1,1),(-1,-1),"CENTER"),
        ("BOTTOMPADDING",(0,0),(-1,-1),8),
        ("TOPPADDING",(0,0),(-1,-1),8),
    ]))
    story.append(table)
    story.append(Spacer(1,18))
    story.append(heading("Professional Summary"))
    story.append(normal(analysis.get("summary","")))
    story.append(Spacer(1,18))
    story.extend(bullet_section("Strengths",analysis.get("strengths",[])))
    story.extend(bullet_section("Weaknesses",analysis.get("weaknesses",[])))
    story.extend(bullet_section("Missing Skills",analysis.get("missing_skills",[])))
    story.extend(bullet_section("Suggestions",analysis.get("suggestions",[])))
    story.extend(bullet_section("Recommended Roles",analysis.get("recommended_roles",[])))
    story.extend(bullet_section("Interview Questions",analysis.get("interview_questions",[])))
    story.append(Spacer(1,12))
    story.append(Paragraph("<para align='center'><font color='#777777'>Generated by CVision • AI Resume Analyzer</font></para>",body_style))
    story.append(Paragraph("<para align='center'><font color='#999999'>© 2026 Sidrah Rashid</font></para>",body_style))
    doc.build(story)
    pdf=buffer.getvalue()
    buffer.close()
    return pdf
